DECLARE
V_FNAME EMPLOYEE.FNAME%TYPE;
V_LNAME EMPLOYEE.LNAME%TYPE;
V_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN
SELECT FNAME, LNAME, SALARY
INTO V_FNAME, V_LNAME, V_SALARY
FROM EMPLOYEE
WHERE SSN=102;
DBMS_OUTPUT.PUT_LINE(V_FNAME||' '||V_LNAME||' '||V_SALARY);
END;
/